name: CI

on:
  pull_request:
    branches: [ main, MAIN ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  push:
    branches: [ desenvolvimentoTiago, desenvolvimentoFernando ]

jobs:
  rls-verify:
    name: Verify RLS gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Run RLS verification SQL
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL_STAGING }}
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then echo "Missing SUPABASE_DB_URL_STAGING secret" && exit 1; fi
          psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f verify_access_levels.sql | cat

  lint-build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Build
        run: npm run build --if-present

  semgrep:
    name: Semgrep Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >
            p/ci
            p/javascript
            p/typescript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  types-gen-check:
    name: Types generation check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Generate types from staging DB
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL_STAGING }}
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then echo "Missing SUPABASE_DB_URL_STAGING secret" && exit 1; fi
          npx supabase@latest gen types typescript --db-url "$SUPABASE_DB_URL" > types.ci.ts
      - name: Compare with repo types
        run: |
          if ! diff -u types.ci.ts src/integrations/supabase/types.ts; then
            echo "Types differ. Please run: npx supabase@latest gen types typescript --db-url \"\$SUPABASE_DB_URL_STAGING\" > src/integrations/supabase/types.ts and commit the result." && exit 1
          fi

  require-all:
    name: Require all checks
    runs-on: ubuntu-latest
    needs: [ rls-verify, lint-build, semgrep, types-gen-check ]
    steps:
      - run: echo "All CI checks passed"